baseURL = "https://jazzforge.com/"
languageCode = "en-us"
title = "Jazz Forge | Learn and practise jazz improvisation"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "JazzForge"
url     = "/"
weight  = 1
[[menu.main]]
name    = "Forums"
url     = "under_construction"
weight  = 2
disabled = true
[[menu.main]]
name    = "Blog"
url     = "under_construction"
weight  = 3
[[menu.main]]
name    = "Contact"
url     = "under_construction"
weight  = 4
[[menu.main]]
name    = "About"
url     = "under_construction"
weight  = 5

# Site Params
[params]
name = "\u00AC JazzForge.com"
home = "JazzForge"
logo = "images/jazzforge.svg"
dateFormat = "6 January 2006"
# Meta data
description = "JazzForge landing page"
author = "Víctor Morilla"
# Google Analitycs
googleAnalyticsID = "G-MWY6K9HYQP"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/collage.png"
heading = "Become a better musician"
description = "JazzForge helps you to develop your improvisation skills. And it is completely free!"
# button
btn     = false
btnText = "GET STARTED"
btnURL  = "https://jazzforge.com/app"

# flip text
[[params.banner.flipText]]
title   = "LEARN"
[[params.banner.flipText]]
title   = "PRACTISE"
[[params.banner.flipText]]
title   = "SHARE"


# Homepage About Section
[params.about]
enable  = true
title   = "About JazzForge"
content = "..."
image   = "images/about/about.png"

# Call to Action
[params.cta]
enable  = true
title   = "What are you waiting for?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Start Now!"
btnURL  = "https://jazzforge.com/app"

# Portfolio Section On Homepage
[params.instructions]
enable  = true
title   = "Easy to use"
subtitle= "JazzForge is simple and intuitive. Take advantage of thousands of standards publicly available and invest more time practising with your instrument."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/JazzForge-105334332054258/"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/jazzforge"

[[params.socialIcon]]
icon = "ion-social-youtube"
url = "https://www.youtube.com/channel/UCKpGHfHUzXC-O2AD-lakGSA"

[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/jazzforge"

[markup.goldmark.renderer]
hardWraps = true